name: Generate Activity Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate activity graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: furqanzubair209-cell
          options: theme=tokyo-night&hide_border=true&area=true&custom_title=Muhammad Furqan's Contribution Graph
          output_path: activity-graph/activity-graph.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit graph
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update activity graph"
          file_pattern: activity-graph/activity-graph.svg
