name: Generate Metrics Dashboard

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN || secrets.GITHUB_TOKEN }}
          user: furqanzubair209-cell
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Karachi
          config_display: large
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: percentage, bytes-size
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
