name: Generate Metrics Dashboard

on:
  schedule:
    - cron: "0 0 * * *"      # once a day
  workflow_dispatch: {}       # lets you trigger it manually from the Actions tab

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate metrics.svg
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: furqanzubair209-cell
          template: classic
          base: "header, activity, community, repositories, metadata"
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_limit: 8
          plugin_habits: yes
          plugin_habits_charts_type: bars
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
